FROM scratch

ADD 0561aaebd1615d5c32ea89046bae95ed11dd004f010944f4445d75053b6e888c.tar.xz /
ADD 52b8805280223a67ee24c1dbdf8dd65ee3657ef604d238a24440f824b4ba6d5e.tar.xz /
ADD 544f5c0ba50d77a25b230b7576e6c81f989bcd7601485430fee1f046d809ef58.tar.xz /
ADD 9cdb4d3fe3e67ed946fbd8d5c27c6a06d8cd00b29dae45430c129e8d35bb52a5.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]
